# Generated by Django 3.2.4 on 2021-06-09 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20210609_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2021, 6, 9, 8, 15, 13, 738852, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
