# Generated by Django 3.2.3 on 2021-06-09 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_employee_joindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joinDate',
        ),
    ]
